In [1]:
import pandas as pd

In [2]:
import os

In [5]:
folder_name = "raw_data"
file_list = os.listdir(folder_name)
file_list

['10,11-16']

In [6]:
file_name = folder_name  + "/" + file_list[0]
file_name

'raw_data/10,11-16'

In [8]:
pd_data = pd.read_csv(file_name)
pd_data

                  timestamp     amount   price symbol
0       2016-10-24 10:33:23  -0.727285  655.93    BTC
1       2016-10-24 10:33:23  -0.869754  655.93    BTC
2       2016-10-24 10:33:23  -0.869672  655.93    BTC
3       2016-10-24 10:33:23  -9.145700  655.93    BTC
4       2016-10-24 10:33:23  -0.869628  655.93    BTC
5       2016-10-24 10:33:23  -0.869603  655.93    BTC
6       2016-10-24 10:33:23  -0.058757  655.93    BTC
7       2016-10-24 10:38:58  -1.520000  655.93    BTC
8       2016-10-24 10:38:58  -1.690000  655.93    BTC
9       2016-10-24 10:43:05  -1.811400  655.51    BTC
10      2016-10-24 10:44:16  -0.152532  655.50    BTC
11      2016-10-24 10:51:02  -4.110000  655.51    BTC
12      2016-10-24 10:54:11  -0.060000  655.50    BTC
13      2016-10-24 11:00:05  -4.079800  655.97    BTC
14      2016-10-24 11:01:02  -0.467600  656.28    BTC
15      2016-10-24 11:01:04  -0.401317  656.28    BTC
16      2016-10-24 11:01:04  -0.223976  656.28    BTC
17      2016-10-24 11:01:42  11.275879  656.29    BTC
18      2016-10-24 11:01:42   1.520000  656.29    BTC
19      2016-10-24 11:01:57  -0.458000  656.51    BTC
20      2016-10-24 11:02:08  -1.520000  656.51    BTC
21      2016-10-24 11:02:08  -5.990000  656.51    BTC
22      2016-10-24 11:02:16   2.490000  656.51    BTC
23      2016-10-24 11:02:16   0.598500  656.51    BTC
24      2016-10-24 11:02:16   0.911500  656.52    BTC
25      2016-10-24 11:06:21   0.034800  656.50    BTC
26      2016-10-24 11:06:53  -0.128755  656.46    BTC
27      2016-10-24 11:06:53  -0.188357  656.46    BTC
28      2016-10-24 11:06:54  -0.074508  656.46    BTC
29      2016-10-24 11:06:54  -0.200525  656.46    BTC
...                     ...        ...     ...    ...
173312  2016-11-21 10:19:45   0.128000  736.89    BTC
173313  2016-11-21 10:19:45   1.180000  737.00    BTC
173314  2016-11-21 10:19:48   0.081200  736.99    BTC
173315  2016-11-21 10:19:51   2.418800  736.99    BTC
173316  2016-11-21 10:19:52  -8.696000  735.91    BTC
173317  2016-11-21 10:19:54   0.046800  737.00    BTC
173318  2016-11-21 10:19:57   0.065000  736.99    BTC
173319  2016-11-21 10:20:01   0.036300  736.99    BTC
173320  2016-11-21 10:20:04   0.013300  736.99    BTC
173321  2016-11-21 10:20:09   0.065000  736.99    BTC
173322  2016-11-21 10:20:12  -0.468000  735.92    BTC
173323  2016-11-21 10:20:13   0.025000  736.99    BTC
173324  2016-11-21 10:20:17   0.037300  736.99    BTC
173325  2016-11-21 10:24:08  -0.000667  735.91    BTC
173326  2016-11-21 10:24:08  -0.133000  735.91    BTC
173327  2016-11-21 10:24:08  -0.130333  735.91    BTC
173328  2016-11-21 10:25:02  -0.000667  735.91    BTC
173329  2016-11-21 10:25:02  -2.499333  735.91    BTC
173330  2016-11-21 10:27:03   0.128000  735.95    BTC
173331  2016-11-21 10:27:03   0.017999  735.95    BTC
173332  2016-11-21 10:30:52   0.131000  735.93    BTC
173333  2016-11-21 10:30:52   0.114000  735.93    BTC
173334  2016-11-21 10:30:52   0.130000  735.93    BTC
173335  2016-11-21 10:30:52   0.131000  735.93    BTC
173336  2016-11-21 10:30:52   0.131000  735.93    BTC
173337  2016-11-21 10:30:52   1.367500  735.97    BTC
173338  2016-11-21 10:30:52   1.000000  735.97    BTC
173339  2016-11-21 10:31:03  -1.083000  736.95    BTC
173340  2016-11-21 10:31:38  -8.106700  736.64    BTC
173341  2016-11-21 10:31:38  -5.543500  736.62    BTC

[173342 rows x 4 columns]

In [9]:
pd_data.columns

Index(['timestamp', 'amount', 'price', 'symbol'], dtype='object')

In [11]:
colum_names = pd_data.columns.tolist()
colum_names

['timestamp', 'amount', 'price', 'symbol']

In [13]:
type(pd_data["price"])

pandas.core.series.Series

In [14]:
pd_data[colum_names[2]]

0         655.93
1         655.93
2         655.93
3         655.93
4         655.93
5         655.93
6         655.93
7         655.93
8         655.93
9         655.51
10        655.50
11        655.51
12        655.50
13        655.97
14        656.28
15        656.28
16        656.28
17        656.29
18        656.29
19        656.51
20        656.51
21        656.51
22        656.51
23        656.51
24        656.52
25        656.50
26        656.46
27        656.46
28        656.46
29        656.46
           ...
173312    736.89
173313    737.00
173314    736.99
173315    736.99
173316    735.91
173317    737.00
173318    736.99
173319    736.99
173320    736.99
173321    736.99
173322    735.92
173323    736.99
173324    736.99
173325    735.91
173326    735.91
173327    735.91
173328    735.91
173329    735.91
173330    735.95
173331    735.95
173332    735.93
173333    735.93
173334    735.93
173335    735.93
173336    735.93
173337    735.97
173338    735.97
173339    736.95
173340    736.64
173341    736.62
Name: price, Length: 173342, dtype: float64

In [15]:
i = 0
for d in colum_names:
    if d == "price":
        break
    else:
        i += 1

In [17]:
pd_data[colum_names[i]]

0         655.93
1         655.93
2         655.93
3         655.93
4         655.93
5         655.93
6         655.93
7         655.93
8         655.93
9         655.51
10        655.50
11        655.51
12        655.50
13        655.97
14        656.28
15        656.28
16        656.28
17        656.29
18        656.29
19        656.51
20        656.51
21        656.51
22        656.51
23        656.51
24        656.52
25        656.50
26        656.46
27        656.46
28        656.46
29        656.46
           ...
173312    736.89
173313    737.00
173314    736.99
173315    736.99
173316    735.91
173317    737.00
173318    736.99
173319    736.99
173320    736.99
173321    736.99
173322    735.92
173323    736.99
173324    736.99
173325    735.91
173326    735.91
173327    735.91
173328    735.91
173329    735.91
173330    735.95
173331    735.95
173332    735.93
173333    735.93
173334    735.93
173335    735.93
173336    735.93
173337    735.97
173338    735.97
173339    736.95
173340    736.64
173341    736.62
Name: price, Length: 173342, dtype: float64

In [22]:
import openpyxl as xl

In [23]:
excel_folder = "xl_data"

In [33]:
wb = xl.Workbook()
sheet = wb.get_active_sheet()
sheet.title = "experiment_data"

C:\Users\saket chaudhry\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated function get_active_sheet (Use the .active property).

In [34]:
names = ["std1", "std2", "std3", "std4"]
roll_no = [1, 2, 3, 4]
eductaion = ["Intermediate", "BSc", "MSc", "BA"]

In [35]:
sheet.cell(row=1, column=1).value = "Roll Number"
sheet.cell(row=1, column=2).value = "Name"
sheet.cell(row=1, column=3).value = "Education"

In [39]:
i = 2
for r, n, e in zip(roll_no, names, eductaion):
    sheet.cell(row=i, column=1).value = r
    sheet.cell(row=i, column=2).value = n
    sheet.cell(row=i, column=3).value = e
    i = i +1

In [41]:
file_name1 = excel_folder + "/" + "exp_data.xlsx"
print(file_name1)
wb.save(file_name1)

xl_data/exp_data.xlsx